# Usar una imagen de Python ligera
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app



# Copiar archivos necesarios
COPY . .
# Instalar dependencias
RUN pip install --no-cache-dir -r requirements-dxcollector.txt

# Comando por defecto (se puede sobrescribir en docker-compose)
CMD ["python3", "dxcollector", "-f", "json"]